require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const mongoose = require('mongoose');
const Restaurant = require('../models/Restaurant');

const RESTAURANTS = [
  // ─── Bandra ───────────────────────────────────────────────────────────────
  {
    name: 'The Table',
    location: { lat: 18.9438, lng: 72.8257 },
    cuisines: ['Continental', 'Modern European'],
    priceRange: 4,
    rating: 4.7,
    reviewCount: 3200,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 9, cozy: 8, loud: 3, workFriendly: 4 },
    crowdLevel: 6,
    aestheticScore: 9,
    address: 'Colaba Causeway, Mumbai',
  },
  {
    name: 'Bastian Bandra',
    location: { lat: 19.0551, lng: 72.8283 },
    cuisines: ['Seafood', 'Continental'],
    priceRange: 4,
    rating: 4.6,
    reviewCount: 5100,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 7, cozy: 6, loud: 7, workFriendly: 3 },
    crowdLevel: 8,
    aestheticScore: 8,
    address: 'Linking Road, Bandra West, Mumbai',
  },
  {
    name: 'Smoke House Deli',
    location: { lat: 19.0560, lng: 72.8299 },
    cuisines: ['European', 'All Day Breakfast'],
    priceRange: 3,
    rating: 4.5,
    reviewCount: 4200,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 6, cozy: 9, loud: 4, workFriendly: 8 },
    crowdLevel: 5,
    aestheticScore: 8,
    address: 'Linking Road, Bandra West, Mumbai',
  },
  {
    name: 'Suzette Bandra',
    location: { lat: 19.0541, lng: 72.8310 },
    cuisines: ['French', 'Crepes', 'Café'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 3800,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 7, cozy: 9, loud: 3, workFriendly: 9 },
    crowdLevel: 4,
    aestheticScore: 9,
    address: 'Chapel Road, Bandra West, Mumbai',
  },
  {
    name: 'Pali Village Café',
    location: { lat: 19.0580, lng: 72.8302 },
    cuisines: ['Continental', 'Indian'],
    priceRange: 2,
    rating: 4.6,
    reviewCount: 2900,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 6, cozy: 8, loud: 4, workFriendly: 7 },
    crowdLevel: 5,
    aestheticScore: 8,
    address: 'Pali Hill, Bandra West, Mumbai',
  },
  {
    name: 'Candies',
    location: { lat: 19.0603, lng: 72.8297 },
    cuisines: ['Bakery', 'Continental', 'Café'],
    priceRange: 1,
    rating: 4.5,
    reviewCount: 6100,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 5, cozy: 9, loud: 5, workFriendly: 8 },
    crowdLevel: 7,
    aestheticScore: 7,
    address: 'Waroda Road, Bandra West, Mumbai',
  },
  {
    name: 'Sequel',
    location: { lat: 19.0521, lng: 72.8329 },
    cuisines: ['Health Food', 'Continental'],
    priceRange: 3,
    rating: 4.5,
    reviewCount: 2400,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 5, cozy: 7, loud: 4, workFriendly: 9 },
    crowdLevel: 4,
    aestheticScore: 8,
    address: 'Hill Road, Bandra West, Mumbai',
  },
  {
    name: 'Hitchki',
    location: { lat: 19.0598, lng: 72.8367 },
    cuisines: ['Indian', 'Street Food'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 3300,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 4, cozy: 6, loud: 8, workFriendly: 4 },
    crowdLevel: 8,
    aestheticScore: 7,
    address: 'Bandra West, Mumbai',
  },

  // ─── Lower Parel / Worli ──────────────────────────────────────────────────
  {
    name: 'Tasting Room',
    location: { lat: 19.0021, lng: 72.8266 },
    cuisines: ['Mediterranean', 'Wine Bar'],
    priceRange: 4,
    rating: 4.7,
    reviewCount: 1800,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 9, cozy: 7, loud: 3, workFriendly: 5 },
    crowdLevel: 4,
    aestheticScore: 9,
    address: 'Worli, Mumbai',
  },
  {
    name: 'Cafe Zoe',
    location: { lat: 18.9990, lng: 72.8219 },
    cuisines: ['European', 'All Day Breakfast'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 4700,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 5, cozy: 9, loud: 4, workFriendly: 9 },
    crowdLevel: 5,
    aestheticScore: 9,
    address: 'Mathuradas Mill Compound, Lower Parel, Mumbai',
  },
  {
    name: 'The Bombay Canteen',
    location: { lat: 19.0025, lng: 72.8248 },
    cuisines: ['Modern Indian'],
    priceRange: 3,
    rating: 4.6,
    reviewCount: 5600,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 6, cozy: 7, loud: 6, workFriendly: 5 },
    crowdLevel: 7,
    aestheticScore: 9,
    address: 'Kamala Mills, Lower Parel, Mumbai',
  },
  {
    name: 'O Pedro',
    location: { lat: 19.0030, lng: 72.8254 },
    cuisines: ['Goan', 'Modern Indian'],
    priceRange: 3,
    rating: 4.7,
    reviewCount: 3100,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 7, cozy: 8, loud: 5, workFriendly: 5 },
    crowdLevel: 6,
    aestheticScore: 9,
    address: 'BKC, Mumbai',
  },
  {
    name: 'Neel',
    location: { lat: 18.9973, lng: 72.8213 },
    cuisines: ['North Indian', 'Mughlai'],
    priceRange: 3,
    rating: 4.5,
    reviewCount: 2200,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 8, cozy: 7, loud: 4, workFriendly: 5 },
    crowdLevel: 5,
    aestheticScore: 8,
    address: 'Lower Parel, Mumbai',
  },
  {
    name: 'Masque',
    location: { lat: 18.9982, lng: 72.8225 },
    cuisines: ['Modern Indian', 'Fine Dining'],
    priceRange: 4,
    rating: 4.8,
    reviewCount: 1200,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 10, cozy: 8, loud: 2, workFriendly: 3 },
    crowdLevel: 3,
    aestheticScore: 10,
    address: 'Laxmi Mills, Lower Parel, Mumbai',
  },

  // ─── Juhu / Andheri ───────────────────────────────────────────────────────
  {
    name: 'Hakkasan Mumbai',
    location: { lat: 19.0760, lng: 72.8777 },
    cuisines: ['Chinese', 'Dim Sum'],
    priceRange: 4,
    rating: 4.6,
    reviewCount: 2800,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 9, cozy: 6, loud: 5, workFriendly: 4 },
    crowdLevel: 6,
    aestheticScore: 9,
    address: 'Sahar Road, Andheri East, Mumbai',
  },
  {
    name: 'Prithvi Café',
    location: { lat: 19.1005, lng: 72.8266 },
    cuisines: ['Continental', 'Snacks', 'Café'],
    priceRange: 1,
    rating: 4.6,
    reviewCount: 7300,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 6, cozy: 10, loud: 4, workFriendly: 8 },
    crowdLevel: 6,
    aestheticScore: 9,
    address: 'Juhu Church Road, Mumbai',
  },
  {
    name: 'The Yellow Chilli',
    location: { lat: 19.1122, lng: 72.8656 },
    cuisines: ['North Indian', 'Punjabi'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 3400,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 5, cozy: 6, loud: 7, workFriendly: 5 },
    crowdLevel: 7,
    aestheticScore: 6,
    address: 'Andheri West, Mumbai',
  },
  {
    name: 'Tamasha',
    location: { lat: 19.0625, lng: 72.8297 },
    cuisines: ['Bar', 'Indian'],
    priceRange: 3,
    rating: 4.5,
    reviewCount: 4100,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 5, cozy: 4, loud: 9, workFriendly: 2 },
    crowdLevel: 9,
    aestheticScore: 7,
    address: 'Bandra West, Mumbai',
  },
  {
    name: 'Bonobo',
    location: { lat: 19.0641, lng: 72.8312 },
    cuisines: ['Bar', 'Continental', 'Live Music'],
    priceRange: 3,
    rating: 4.5,
    reviewCount: 2600,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 6, cozy: 5, loud: 9, workFriendly: 2 },
    crowdLevel: 9,
    aestheticScore: 8,
    address: 'Bandra West, Mumbai',
  },

  // ─── Colaba ───────────────────────────────────────────────────────────────
  {
    name: 'Leopold Cafe',
    location: { lat: 18.9222, lng: 72.8318 },
    cuisines: ['Continental', 'Indian', 'Beer Garden'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 11000,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 4, cozy: 5, loud: 8, workFriendly: 4 },
    crowdLevel: 9,
    aestheticScore: 7,
    address: 'Colaba Causeway, Mumbai',
  },
  {
    name: 'Indigo',
    location: { lat: 18.9245, lng: 72.8328 },
    cuisines: ['Continental', 'Mediterranean'],
    priceRange: 4,
    rating: 4.7,
    reviewCount: 3900,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 9, cozy: 8, loud: 3, workFriendly: 6 },
    crowdLevel: 5,
    aestheticScore: 9,
    address: 'Mandlik Road, Colaba, Mumbai',
  },
  {
    name: 'Café Mondegar',
    location: { lat: 18.9232, lng: 72.8314 },
    cuisines: ['Continental', 'Café'],
    priceRange: 1,
    rating: 4.5,
    reviewCount: 8200,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 4, cozy: 6, loud: 7, workFriendly: 5 },
    crowdLevel: 8,
    aestheticScore: 7,
    address: 'Metro House, Colaba, Mumbai',
  },
  {
    name: 'Theobroma Colaba',
    location: { lat: 18.9201, lng: 72.8322 },
    cuisines: ['Bakery', 'Desserts', 'Café'],
    priceRange: 1,
    rating: 4.6,
    reviewCount: 9100,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 5, cozy: 8, loud: 5, workFriendly: 7 },
    crowdLevel: 7,
    aestheticScore: 7,
    address: 'Colaba Causeway, Mumbai',
  },
  {
    name: 'Bademiya',
    location: { lat: 18.9248, lng: 72.8306 },
    cuisines: ['Kebab', 'Street Food', 'Mughlai'],
    priceRange: 1,
    rating: 4.5,
    reviewCount: 12000,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 2, cozy: 3, loud: 9, workFriendly: 2 },
    crowdLevel: 10,
    aestheticScore: 4,
    address: 'Tulloch Road, Colaba, Mumbai',
  },

  // ─── Fort / CST ───────────────────────────────────────────────────────────
  {
    name: 'The Pantry',
    location: { lat: 18.9312, lng: 72.8355 },
    cuisines: ['Continental', 'Café', 'Brunch'],
    priceRange: 2,
    rating: 4.6,
    reviewCount: 3600,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 6, cozy: 9, loud: 3, workFriendly: 9 },
    crowdLevel: 4,
    aestheticScore: 9,
    address: 'Aarti Chambers, Fort, Mumbai',
  },
  {
    name: 'Britannia & Co',
    location: { lat: 18.9345, lng: 72.8386 },
    cuisines: ['Parsi', 'Iranian Café'],
    priceRange: 1,
    rating: 4.7,
    reviewCount: 5800,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 5, cozy: 8, loud: 4, workFriendly: 6 },
    crowdLevel: 7,
    aestheticScore: 8,
    address: 'Sprott Road, Ballard Estate, Mumbai',
  },
  {
    name: 'Kala Ghoda Café',
    location: { lat: 18.9280, lng: 72.8322 },
    cuisines: ['Continental', 'Café'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 4400,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 5, cozy: 9, loud: 3, workFriendly: 9 },
    crowdLevel: 4,
    aestheticScore: 9,
    address: 'Ropewalk Lane, Kala Ghoda, Mumbai',
  },
  {
    name: 'Khyber',
    location: { lat: 18.9349, lng: 72.8381 },
    cuisines: ['North Indian', 'Mughlai'],
    priceRange: 3,
    rating: 4.6,
    reviewCount: 4900,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 7, cozy: 7, loud: 5, workFriendly: 6 },
    crowdLevel: 6,
    aestheticScore: 8,
    address: 'MG Road, Fort, Mumbai',
  },

  // ─── Powai ────────────────────────────────────────────────────────────────
  {
    name: 'Aaliya\'s',
    location: { lat: 19.1190, lng: 72.9061 },
    cuisines: ['Lebanese', 'Mediterranean'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 2100,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 7, cozy: 8, loud: 4, workFriendly: 7 },
    crowdLevel: 4,
    aestheticScore: 8,
    address: 'Hiranandani Gardens, Powai, Mumbai',
  },
  {
    name: 'Nom Nom',
    location: { lat: 19.1188, lng: 72.9079 },
    cuisines: ['Asian', 'Pan-Asian'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 1900,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 6, cozy: 7, loud: 5, workFriendly: 7 },
    crowdLevel: 5,
    aestheticScore: 7,
    address: 'Hiranandani Gardens, Powai, Mumbai',
  },
  {
    name: 'Koyla',
    location: { lat: 19.1175, lng: 72.9055 },
    cuisines: ['Kebab', 'North Indian'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 2800,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 6, cozy: 6, loud: 6, workFriendly: 5 },
    crowdLevel: 7,
    aestheticScore: 7,
    address: 'Powai, Mumbai',
  },

  // ─── Versova / Madh Island ────────────────────────────────────────────────
  {
    name: 'Aksa Beach Shack',
    location: { lat: 19.1738, lng: 72.8154 },
    cuisines: ['Seafood', 'Continental'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 1700,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 8, cozy: 7, loud: 5, workFriendly: 3 },
    crowdLevel: 5,
    aestheticScore: 8,
    address: 'Aksa Beach, Malad West, Mumbai',
  },
  {
    name: 'Versova Social',
    location: { lat: 19.1302, lng: 72.8144 },
    cuisines: ['Continental', 'Bar', 'Café'],
    priceRange: 2,
    rating: 4.5,
    reviewCount: 3200,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 5, cozy: 7, loud: 7, workFriendly: 8 },
    crowdLevel: 7,
    aestheticScore: 8,
    address: 'Versova, Andheri West, Mumbai',
  },

  // ─── Quick bites (low crowd, fast) ───────────────────────────────────────
  {
    name: 'A Taste of Kerala',
    location: { lat: 19.0183, lng: 72.8408 },
    cuisines: ['Kerala', 'South Indian'],
    priceRange: 1,
    rating: 4.6,
    reviewCount: 4300,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 3, cozy: 6, loud: 5, workFriendly: 6 },
    crowdLevel: 4,
    aestheticScore: 5,
    address: 'Matunga, Mumbai',
  },
  {
    name: 'Cafe Mysore',
    location: { lat: 19.0281, lng: 72.8435 },
    cuisines: ['South Indian', 'Udupi'],
    priceRange: 1,
    rating: 4.5,
    reviewCount: 6700,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 2, cozy: 5, loud: 6, workFriendly: 6 },
    crowdLevel: 6,
    aestheticScore: 4,
    address: 'Matunga West, Mumbai',
  },
  {
    name: 'Swati Snacks',
    location: { lat: 18.9674, lng: 72.8076 },
    cuisines: ['Gujarati', 'Chaat'],
    priceRange: 1,
    rating: 4.7,
    reviewCount: 8800,
    source: 'admin',
    priorityScore: 4,
    vibeScores: { romantic: 3, cozy: 6, loud: 6, workFriendly: 5 },
    crowdLevel: 8,
    aestheticScore: 6,
    address: 'Tardeo, Mumbai',
  },
  {
    name: 'Olympia Coffee House',
    location: { lat: 18.9211, lng: 72.8308 },
    cuisines: ['Iranian Café', 'Snacks'],
    priceRange: 1,
    rating: 4.5,
    reviewCount: 5100,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 3, cozy: 7, loud: 5, workFriendly: 7 },
    crowdLevel: 5,
    aestheticScore: 7,
    address: 'Ormiston Road, Colaba, Mumbai',
  },
  {
    name: 'Sarvi Restaurant',
    location: { lat: 18.9698, lng: 72.8299 },
    cuisines: ['Mughlai', 'Kebab'],
    priceRange: 1,
    rating: 4.5,
    reviewCount: 3900,
    source: 'curated',
    priorityScore: 3,
    vibeScores: { romantic: 2, cozy: 4, loud: 7, workFriendly: 4 },
    crowdLevel: 8,
    aestheticScore: 4,
    address: 'Bhendi Bazaar, Mumbai',
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/where-to');
    console.log('Connected to MongoDB');

    let inserted = 0;
    let skipped = 0;

    for (const data of RESTAURANTS) {
      try {
        await Restaurant.create(data);
        inserted++;
      } catch (err) {
        if (err.code === 11000) {
          skipped++;
        } else {
          console.error(`Failed to insert "${data.name}":`, err.message);
        }
      }
    }

    console.log(`Seed complete: ${inserted} inserted, ${skipped} skipped (duplicates)`);
  } catch (err) {
    console.error('Seed failed:', err.message);
  } finally {
    await mongoose.disconnect();
  }
};

seed();
